### ISSUE TITLE
package is not on npm

### ISSUE THREAD

**Issue by julienbachmann** [Clarifai/clarifai-javascript#1]
Hello,

Could you please add it to npm?

Thanks

Juliej

**Comment by dankantor** [comment]
@julienbachmann coming very soon. I'll let you know here as soon as we do.

**Comment by joeyslack** [comment]
As another API user, just do `npm install https://github.com/Clarifai/clarifai-javascript --save` in your project, if you want to add the dependency in your package.json, until they have the package available in the global NPM registry.

**Comment by homerjam** [comment]
+1

**Comment by cbelth** [comment]
Having run "npm install https://github.com/Clarifai/clarifai-javascript --save" as @joeyslack suggested, I installed browserify as well and set it up properly (I confirmed this with other modules). However when I include "var Clarifai = require('../../clarifai-javascript');" where it points to the repository generated by npm, I get "Uncaught Error: Cannot find module '../../clarifai-javascript'". I'm new to browserify and clarifai. Does anyone know what I am doing incorrectly?

**Comment by joeyslack** [comment]
Hey @cbelth 

The module is named as 'clarifai' in this current version, so you'll have to change your require path to be (in your case): var Clarifai = require('../../clarifai');  

So in summary, the package name is actually 'clarifai' not 'clarifai-javascript' as you'd assume (I'm guessing that's what it WILL be once the new version is on npm packages.

**Comment by cbelth** [comment]
Thanks for the quick response. It is still not working. You mentioned adding the dependency in my package.json. Do I need to add something like "clarifai": "^1.2.0" under devDependencies? Also, I ran the npm install from my home directory. @joeyslack

**Comment by joeyslack** [comment]
When you run 'npm install ... --save', the --save part is telling it to add
an entry into your packages.json. So if you look at your package.json, you
should see clarifai in there. If it's not there, you'll have to add it, or
re-run the install command (no harm in doing that).

**Comment by dankantor** [comment]
We are now on NPM https://www.npmjs.com/package/clarifai

Would love any and all feedback. Thanks!
