### ISSUE TITLE
How can I use the OCR model?

### ISSUE THREAD

**Issue by Eyesonly88** [Clarifai/clarifai-javascript#11]
The blog (http://blog.clarifai.com/the-ultimate-visual-recognition-api-guide/#2) mentions the ability to recognize text but I can't find the model to use for that?

_Public Models_
![image](https://cloud.githubusercontent.com/assets/767013/22611717/05275e1c-ead1-11e6-9c7e-7c81ae21749c.png)

Is the OCR model available but not documented? if so how can I use it?

Thanks 👍

**Comment by dankantor** [comment]
Sorry we don't currently offer an OCR model. We will let you know when we do.
