### ISSUE TITLE
Error with es2015 preset

### ISSUE THREAD

**Issue by FrankSalad** [Clarifai/clarifai-javascript#17]
Trying to deploy the latest clarifai pulled from npm in my react-native app:
![simulator screen shot may 24 2017 9 53 09 pm](https://cloud.githubusercontent.com/assets/2359644/26436541/116d6aa8-40cc-11e7-8fbb-de1736a03c34.png)

(note, the paths shown are not absolute `/node_modules`, I obscured the root project dir name)

**Comment by FrankSalad** [comment]
I resolved it by setting my .bablrc like so:

```

**Comment by yipcma** [comment]
I'm facing the same problem, hope it can get rectified soon in the npm package. Thanks a lot.

**Comment by maxcell** [comment]
Just wanted to check in with everyone, is this still a problem now in `2.1.8`?

**Comment by DZamataev** [comment]
@maxcell Facing same error in ```2.1.8```
![screenshot_2017-05-30-17-15-49-506_com vpr](https://cloud.githubusercontent.com/assets/2046717/26587752/e497faf4-455b-11e7-9190-71184789b39a.png)

**Comment by DZamataev** [comment]
After I do ```npm install babel-preset-es2015 --save``` and do the standard mantra with node_modules cleaning and cache reseting I get another error:
![screenshot_2017-05-30-17-52-41-753_com vpr](https://cloud.githubusercontent.com/assets/2046717/26589655/33bf18ba-4561-11e7-8cd3-c4bb549dda86.png)

**Comment by DZamataev** [comment]
BTW, version 2.0.18 seems to integrate just fine.
```npm install clarifai@2.0.18 --save```

**Comment by maxcell** [comment]
I am just rehashing this from #19:
>Howdy all! I have been fiddling around for a bit and I am curious if this will have any impact to what you are doing. I have also tried this on two different node versions: `v6.10.3` and `v8.1.4`. Going from a clean installs on both:
>
>1. Cleaning your cache: `npm cache --force clean`
>a. For just in case, be sure to remove your `node_modules` folder.
>2. Then `npm install`, you will get all your node modules again
>3. Install clarifai `npm install clarifai --save`
>a. If in case you are getting babel errors, I would also go `npm install babel-preset-es2015 --save`
>4. I also run react native using the `react-native-cli`
>a. If you want to install this, go ahead and `npm install react-native-cli`
>5. And finally you can run with `react-native run-ios` `react-native run-android` or simply using your `npm start`

**Comment by eddiezane** [comment]
Going to close this and continue tracking in #19. Looking into this now.
