### ISSUE TITLE
clarifai javascript client no longer works as of a couple of hours ago

### ISSUE THREAD

**Issue by scottbouma** [Clarifai/clarifai-javascript#18]
Just this morning clarifai stopped working for me (specific error was "cannot find module 'clarifai' at ...")

I tried deleting/re-npm-installing my node_modules; same issue; I switched my package.json to install 2.1.6 instead of ^2.1.6 and now everything works again.

So I think something is not quite right with your recent 2.1.7 release.

**Comment by kunal732** [comment]
@scottbouma thanks for bringing this to our attention. We're looking into it.

**Comment by maxcell** [comment]
@scottbouma @jChanceHud @Gi-lo @jannevickholm Howdy everyone! Super awesome catch with this! Recently we changed our build process and so it didn't generate our `dist/` folder. If you install `2.1.8` it should be all fixed now!

`npm install clarifai@2.1.8 --save` should get you all you need! If anything else comes up, let me know!

**Comment by harsh021102** [comment]
@maxcell I am making a face detection ap using clarifai but its showing error when I declare my API KEY 
const app = new Clarifai.App({
  apiKey: "44c3d5e6225f49b2bfb4bb9fd22d61f2"
});
![Screenshot 2022-06-06 013232](https://user-images.githubusercontent.com/97454359/172068437-110f6312-5a78-4202-ba4e-e1b6c4b56acd.jpg)

**Comment by amandevopsreal** [comment]
Same issue
