### ISSUE TITLE
Handling Responses

### ISSUE THREAD

**Issue by cbelth** [Clarifai/clarifai-javascript#2]
Each of the examples concludes with something like this:

```
handleResponse,
handleError
```

However, it is not very clear _how_ we handle a response. There are no response parameters in the getTags requests. How do we see a response/error?

**Comment by yjkimjunior** [comment]
If you take a look at the directory examples/ and file node-example.js, at the bottom of the source you can see an example of how to handle the response. 

`function handleResponse(response){
  console.log('promise response:', JSON.stringify(response));
};

function handleError(err){
  console.log('promise error:', err);
};
`

**Comment by majman** [comment]
you can also check out the guide for examples of response data: https://developer.clarifai.com/guide/tag#guide-tag-responses
