### ISSUE TITLE
process.nextTick is not a function

### ISSUE THREAD

**Issue by yaibait** [Clarifai/clarifai-javascript#20]
I try import clarifai to my react native project , when I try  

```javascript
const ClarifaiApp = new Clarifai.App({
  apiKey: 'xxxx'
 });

ClarifaiApp.models.predict(Clarifai.GENERAL_MODEL, "https://samples.clarifai.com/metro-north.jpg").then(
      function(response) {
        // do something with response
        console.log(response);
      },
      function(err) {
        console.log(err);
        // there was an error
      }
    );
  }
```

I get error `process.nextTick is not a function`

**Comment by eddiezane** [comment]
@yaibait it looks like React Native doesn't have a `process.nextTick`.

We'll look into a better solution for this but for now you can polyfill it with [`setImmediate`](https://facebook.github.io/react-native/docs/timers.html)

Add this somewhere near the top of your entrypoint:

```javascript
process.nextTick = setImmediate
```

**Comment by yaibait** [comment]
@eddiezane  thanks you, it work for me

**Comment by eddiezane** [comment]
@yaibait glad to hear. Going to keep this open until we find a permanent fix.

**Comment by eddiezane** [comment]
From the research I've done it seems that polyfilling this is expected by the React Native developer.

Maybe in the future our build tools will avoid this issue entirely.

If anyone finding this issue in the future has any advice otherwise we're all ears!

**Comment by tetreault** [comment]
thanks @eddiezane - fixed the nextTick error on my end!

**Comment by sherawat-Lokesh** [comment]
I try to import Clarifai in  my react project the i got this error.

const app = new Clarifai.App({
  apiKey: "af5a54585af246268c4c47d1cb9bf816",
});

app.models.predicct(Clarifai.FACE_DETECT_MODEL, this.state.input).then(
      function (response) {
        console.log(response);
      },
      function (error) {}
    );

i got error : Uncaught ReferenceError: process is not defined
