### ISSUE TITLE
Missing `dist` folder when installing 2.3.0 using NPM

### ISSUE THREAD

**Issue by urnix** [Clarifai/clarifai-javascript#22]
Hi guys.

We use Clarifai 2.2.0 in our project:
```
{
   ...
  "dependencies": {
   ...
    "clarifai": "^2.2.0",
   ...
  }
}

```

Today we noticed that version 2.3.0 released.

And immediately there was an error:
```
Error: Can't find npm module 'clarifai'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```

We also noticed that there is no `dist` folder in  node_modules:
<img width="535" alt="screen shot 2017-09-01 at 17 03 07" src="https://user-images.githubusercontent.com/7656366/29973652-faabf724-8f38-11e7-9785-9f67e925ef84.png">
<img width="520" alt="screen shot 2017-09-01 at 17 01 34" src="https://user-images.githubusercontent.com/7656366/29973667-069c2978-8f39-11e7-942a-51cd6ba638d2.png">

**Comment by eddiezane** [comment]
@urnix so sorry about that. I just unpublished `2.3.0` while we figure out what's wrong with the build.

**Comment by urnix** [comment]
@eddiezane Thanks for the quick response :)
Please write here when it will be fixed.

**Comment by eddiezane** [comment]
@urnix just cut a `2.3.2` release that should be working!

Thanks again for reporting this - can you please shoot me an email at eddie [at] clarifai [dot] com? I want to hook you up with some swag!
