### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by B3zo0** [Clarifai/clarifai-javascript#27]
Would you consider adding typescript support?

**Comment by rok-povsic** [comment]
@B3zo0  Adding Typescript support is something we're looking into. We're aware of the demand for this so it's quite high in our priority list. But we're not Typescript developers so we'll have to learn how this is properly done.

**Comment by kbanta11** [comment]
Was this ever added? (it doesn't look like I can find a @types file for this package). I'm trying to build a typescript react app, so the nodejs grpc package does not work (cannot work in react in browser), and this one does not work due to typescript.
