### ISSUE TITLE
React Native: Dependency Axios throws error 'urlParsingNode.setAttribute is undefined'

### ISSUE THREAD

**Issue by Harshit369** [Clarifai/clarifai-javascript#29]
"isURLSameOrigin.js" file from axios throws error `urlParsingNode.setAttribute is undefined`. where i found this suspicious looking code.
```js
var urlParsingNode = document.createElement('a');
```

**Comment by rok-povsic** [comment]
@Harshit369 Any help fixing this is appreciated, we don't have lots of experience with React Native.

**Comment by Harshit369** [comment]
@rok-povsic I just checked back in `axios@1.11.0` and found that they didn't use to support react-native. But they do now in there latest `v0.18.0` release and check the environment.
exacly [here](https://github.com/axios/axios/blob/d59c70fdfd35106130e9f783d0dbdcddd145b58f/lib/helpers/isURLSameOrigin.js#L6).

**Comment by Harshit369** [comment]
So, i think you can just update axios to its latest stable version in your dependencies and that will do. 🤟
