### ISSUE TITLE
Clarifai app keeps installing without declaration file

### ISSUE THREAD

**Issue by abrown945** [Clarifai/clarifai-javascript#33]
I cannot progress with the creation of my React app because the declaration file is not downloading with the package. I tried 'npm install @types/clarifai' but it said that the latest wasn't available which was confusing.

I tried redoing the entire app to make sure but I am having the same issue. It is not installing with everything else or cannot be found by my text editor.

Why would it not be installing and what can I do to resolve this issue?

**Comment by dcirne** [comment]
@abrown945 could you send us a gist or sample program reproducing the issue you are describing?
