### ISSUE TITLE
Initial 400 error: 11103 Method Not Allowed before face recognition api runs normally

### ISSUE THREAD

**Issue by abrown945** [Clarifai/clarifai-javascript#34]
I have an issue in which the first image or two URL address is not accepted and I am met with the following:

Failed to load resource: the server responded with a status of 400 (Bad Request)

When I click on the link provided, it leads to a page with this on a single line.

 {"status":{"code":11103,"description":"Method not allowed","details":"Method Not Allowed"}}

However, if I try another image and then go back to the original image used the server accepts the image.

Why is my request not accepted until I try enough images?

**Comment by rok-povsic** [comment]
@abrown945 Hi, I'm having trouble understanding what the problem is. From the response you get it seems that an incorrect GET/POST/PATCH/DELETE method is being sent to the server, but I'm unsure where this is coming from.

Can you post a snippet of your JavaScript code where you use the Clarifai JS library that leads to this error?

Thanks

**Comment by abrown945** [comment]
Sure. The problem is that I initially get a 11103 error when I use the app integrated with the face recognition api after it open. However, the error goes away after using a couple of additional photos.

![Screenshot (50)](https://user-images.githubusercontent.com/23192489/54832162-0687a580-4c92-11e9-80ea-8df850a39cd0.png)

I have the code associated with the error placed above the console. I see additional details above the red highlighted text in the console, that may help

**Comment by rok-povsic** [comment]
@abrown945 Hi, if I understand this correctly, the issue occurs on first execution of the `onButtonSubmit` function, but not at any later point?

 Can you print out `imageUrl` and check if, at all times, the value passed in as `imageUrl` is a valid image URL?

**Comment by abrown945** [comment]
Its always a valid address because when the error eventually goes away I can use the same URL to have the face detected.

**Comment by abrown945** [comment]
And yes, it occurs on the first execution of the `onButtonSubmit` function per launch. Once that execution error goes away, I no longer have any error with the api

**Comment by rok-povsic** [comment]
@abrown945 From the code snippet I don't see where the issue occurs. Can you please expand the `data` field in the response object? It may tell us the source of the error.

**Comment by abrown945** [comment]
I just opened up the app and now I can't reproduce the error. Due to this, I can't provide any additional information and will close this for now. 

I appreciate your assistance and if this error occurs again as I have made no changes to my code, I will be sure to follow your additional instructions. Thank you for your time
