### ISSUE TITLE
Cannot use application because of dupes

### ISSUE THREAD

**Issue by soares-luan** [Clarifai/clarifai-javascript#35]
When trying to list my applications, i receive the error
"Object has a duplicate ID; another object with same ID already exist.","details":"Object has a duplicate ID; another object with same ID already exist"
and i cannot list my applications on the platform.
And i cannot remove the duplicateds too, because i dont know what is the duplicated resource
[https://imgur.com/a/9gW72FV](url)

**Comment by rok-povsic** [comment]
Hi @soares-luan, I don't believe this is an issue concerning the Clarifai JS client. Please contact [Clarifai Support](https://www.clarifai.com/developer/support) directly. Thanks!
