### ISSUE TITLE
Update axios dependency

### ISSUE THREAD

**Issue by asjadjawed** [Clarifai/clarifai-javascript#37]
The axios package in use is outdated & vulnerable.
Please update

**Comment by Omaralon** [comment]
What can we do in this scenario, because updating the axios package by itself will affect the way the clarifai API works, right?

**Comment by willianwelbert** [comment]
Also got axios as a vulnerability:
<img width="573" alt="Captura de Tela 2019-08-05 às 18 09 13" src="https://user-images.githubusercontent.com/10202975/62495425-3b614880-b7ac-11e9-873e-04a5058d9070.png">

**Comment by Omaralon** [comment]
Yeap, seems like we're taking the same Udemy course, rock on, dude!

**Comment by rok-povsic** [comment]
Hello, we've released a new version 2.9.1 where the range of the allowed axios versions has been relaxed to include the latest one.

Thanks for letting us know about this issue!
