### ISSUE TITLE
Promise always polyfilled (Incompatible with Angular 2)

### ISSUE THREAD

**Issue by orgbx** [Clarifai/clarifai-javascript#4]
Hi, I'm implementing clarifai-javascript in an app with NativeScript and Angular 2.

It actually breaks the app with this error message:

```
Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
```

I'm seeing that you are always using the es6-promise polyfill 

```
var Promise = require('es6-promise').Promise;) 
```

disregarding if an implementation (custom one in this case) is already available.

See this similar issue https://github.com/Stuk/jszip/issues/303#issuecomment-233723523 and it's fix: https://github.com/Stuk/jszip/pull/321

Cheers!

**Comment by orgbx** [comment]
It actually seems that es6-promise is currently incompatible as it polyfills by default.

**Comment by jared-clarifai** [comment]
Thanks for letting us know! Looking into this

**Comment by alpinparker** [comment]
I'm not sure if this is the same issue, but I'm also trying to run Clarifai on NativeScript with Angular 2 and I get an error when I instantiate the class - `const app = Clarifai.App(...)`:
`JS: Error: Uncaught (in promise): ReferenceError: process is not defined`

When I add `{apiEndpoint: 'https://api.clarifai.com'}` to the constructor, it instantiates the class but when I run `app.models.predict(...)` it gives me an error similar (but different) to the previous one: `JS: ReferenceError: process is not defined`

any fixes or workarounds?

**Comment by eddiezane** [comment]
Sorry for the delay on this. I'm looking into conditionally polyfilling to not break existing apps.

In the future we'll probably remove our Promise polyfill entirely and make you provide your own if you need to.

**Comment by eddiezane** [comment]
We closed this with https://github.com/Clarifai/clarifai-javascript/commit/1cc89bb0a640279bd7ca4c8fcd20b946de027ecf

In the future when we can make a breaking release we'll remove the polyfill entirely.
