### ISSUE TITLE
App.models.list returns empty Models

### ISSUE THREAD

**Issue by lukaszmoroz** [Clarifai/clarifai-javascript#6]
``` javascript
app.models.list().then(response => {
  console.log(response)
})
```

Response doesn't contain any models, even global ones. What am I missing?

**Comment by maxcell** [comment]
@lukaszmoroz You have exactly the right snippet 😄. Response will be an Array of Model objects so if you want to see their name/id or anything else about them you would access them through the object's keys `response[index].id` or `response[index].name`.

I'm gonna mark this as closed. Feel free to respond back if this hasn't been resolved.
