### ISSUE TITLE
Any idea when color will be added?

### ISSUE THREAD

**Issue by kristof** [Clarifai/clarifai-javascript#8]
I'd like to use color in a project and I'm already using this client, is there any timing of when this will be added or any ideas how I can easily integrate color with this client without having to do authentication myself.

Thanks!

**Comment by cmisenas** [comment]
@kristof this is already supported in v1 and in v2, there's an alias for model ids you can pass to the predict function (example below) ([list of other supported models](https://github.com/Clarifai/clarifai-javascript/blob/a8945693ecddd87ed9a75f588178f332da13b492/src/index.js#L5-L13) ).You can see more docs [here](https://developer-preview.clarifai.com/quick-start/).

```
// predict the contents of an image by passing in a url
app.models.predict(Clarifai.GENERAL_MODEL, 'https://samples.clarifai.com/metro-north.jpg').then(
  function(response) {
    console.log(response);
  },
  function(err) {
    console.error(err);
  }
);
```
