### ISSUE TITLE
Default Language Option is not working at javascript api

### ISSUE THREAD

**Issue by rippertnt** [Clarifai/clarifai-javascript#9]
Hello. I am so glad to use your amazing service in Korea.
I have adapted your api to my humanoid robot's vision system.
I have changed the default language english to korean, but results from javascript api have shown just english. How can I resolve this problem?

**Comment by cmisenas** [comment]
Hi @rippertnt the default language only works for v1 (`clarifai@1.2.1`) right now. But stay tuned for v2 support.

**Comment by iamWh1sp3r** [comment]
Any update on supporting other languages on the V2 api ?

**Comment by jared-clarifai** [comment]
Hey @iamWh1sp3r! This is now documented at:

https://developer.clarifai.com/guide/languages#languages

Let us know if you have any questions on it.
